GET http://localhost:3001/api/orders
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOiI1ZjMzYTM4MzBkZDdmYzZjMDg1YTM3ZTMiLCJpYXQiOjE1OTcyMjAzOTR9.4LDfD753IoON8pjI4JK7itqTMP9himU1OQb1dDppO5s
